#!/usr/bin/env bash
set -Eeuo pipefail
SITE_BASE="${ANDRIK_SITE_BASE:-https://andrikmetal.com}"; STAMP="$(date +%Y%m%d-%H%M%S)"
AGENT_URL="${SITE_BASE%/}/radio247/vm-lite/andrik-radio-web-agent-r803.mjs?t=$(date +%s)"; SCREEN_URL="${SITE_BASE%/}/radio247/vm-lite/andrik-radio-screen-restore-r926?t=$(date +%s)"; GOLD_URL="${SITE_BASE%/}/radio247/vm-lite/andrik-radio-air-restore-r925?t=$(date +%s)"; R974_URL="${SITE_BASE%/}/radio247/vm-lite/andrik-fullscreen-visual-r974?t=$(date +%s)"
TA="$(mktemp /tmp/andrik-agent-r1015.XXXXXX.mjs)"; TS="$(mktemp /tmp/andrik-screen-r1015.XXXXXX.sh)"; TG="$(mktemp /tmp/andrik-gold-r1015.XXXXXX.sh)"; TR="$(mktemp /tmp/andrik-r974-r1015.XXXXXX.sh)"; trap 'rm -f "$TA" "$TS" "$TG" "$TR"' EXIT
curl -fsSL --retry 6 --retry-delay 2 "$AGENT_URL" -o "$TA"; curl -fsSL --retry 6 --retry-delay 2 "$SCREEN_URL" -o "$TS"; curl -fsSL --retry 6 --retry-delay 2 "$GOLD_URL" -o "$TG"; curl -fsSL --retry 6 --retry-delay 2 "$R974_URL" -o "$TR"
node --check "$TA"; bash -n "$TS"; bash -n "$TG"; bash -n "$TR"; grep -Fq "AGENT_VERSION_R803='R1015'" "$TA"; grep -Fq 'diskRootR1015' "$TA"; grep -Fq 'ANDRIK R1015 · ВОССТАНОВИТЬ ЭКРАН' "$TS"; grep -Fq 'GOLD-FULL-LATEST.tar.gz' "$TG"; ! grep -Fq '/control/full-fit' "$TS" || grep -Fq 'НЕ ИСПОЛЬЗОВАН' "$TS"
install_one(){ local src="$1" dst="$2" mode="$3"; [ -f "$dst" ] && cp -a "$dst" "$dst.before-R1015-$STAMP"; install -m "$mode" "$src" "$dst"; }
install_one "$TA" /usr/local/lib/andrik-radio-web-agent-r803.mjs 0755; install_one "$TS" /usr/local/sbin/andrik-radio-screen-restore-r926 0755; install_one "$TG" /usr/local/sbin/andrik-radio-air-restore-r925 0755; install_one "$TR" /usr/local/sbin/andrik-fullscreen-visual-r974 0755
for old in /usr/local/lib/andrik-radio-web-agent-r721.mjs /usr/local/lib/andrik-radio-web-agent-r802.mjs; do [ -f "$old" ] && install_one "$TA" "$old" 0755 || true; done
unit_exists(){ systemctl list-unit-files --type=service --no-legend 2>/dev/null | awk '{print $1}' | grep -Fxq "$1"; }; unit_active(){ systemctl is-active --quiet "$1" 2>/dev/null; }; CANON=''; if unit_exists andrik-radio-web.service && unit_active andrik-radio-web.service; then CANON=andrik-radio-web.service; elif unit_exists andrik-radio-web-agent.service && unit_active andrik-radio-web-agent.service; then CANON=andrik-radio-web-agent.service; elif unit_exists andrik-radio-web.service; then CANON=andrik-radio-web.service; elif unit_exists andrik-radio-web-agent.service; then CANON=andrik-radio-web-agent.service; else echo '❌ web-agent service not found'; exit 40; fi
RADIO_BEFORE="$(systemctl show -p MainPID --value andrik-radio.service 2>/dev/null || true)"; systemctl restart "$CANON"; sleep 3; RADIO_AFTER="$(systemctl show -p MainPID --value andrik-radio.service 2>/dev/null || true)"; echo "✅ WEB AGENT=$CANON · $(systemctl is-active "$CANON" || true)"; echo "RADIO PID BEFORE=$RADIO_BEFORE"; echo "RADIO PID AFTER =$RADIO_AFTER"; [ "$RADIO_BEFORE" = "$RADIO_AFTER" ] || echo '⚠️ radio PID changed externally'; echo '✅ R1015 disk telemetry + screen restore + latest GOLD restore installed'; echo '✅ installer did NOT restart radio service'
